[package]
publish = false
name = "tone-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.0"
k9api-dsp = { version = "0.1.0", path = "../../dsp" }
